#!/bin/sh
set -eu

config_file="${1:-.config}"

for option in \
    IPV6 BRIDGE BRIDGE_NETFILTER NF_TABLES_BRIDGE \
    NETFILTER_XTABLES_LEGACY \
    IP_NF_IPTABLES_LEGACY IP6_NF_IPTABLES_LEGACY \
    IP6_NF_IPTABLES IP6_NF_FILTER IP6_NF_NAT \
    IP_NF_TARGET_MASQUERADE IP6_NF_TARGET_MASQUERADE \
    NETFILTER_XT_TARGET_MASQUERADE NF_NAT_MASQUERADE \
    NFT_COMPAT NFT_MASQ NFT_NAT \
    VETH TUN NF_TABLES NF_NAT NETFILTER OVERLAY_FS FUSE_FS \
    EXT4_FS_SECURITY SQUASHFS_XATTR SQUASHFS_ZSTD \
    DECOMPRESS_ZSTD ZSTD_DECOMPRESS \
    IKCONFIG IKCONFIG_PROC BINFMT_MISC \
    RFKILL LEDS_CLASS CFG80211 MAC80211 RTW88 BT \
    USB USB_SUPPORT WLAN \
    RTW88_8821AU RTW88_8812AU RTW88_8814AU \
    FW_LOADER_COMPRESS FW_LOADER_COMPRESS_ZSTD UNICODE \
    USB_XHCI_HCD USB_XHCI_PCI USB_STORAGE USB_UAS \
    SCSI BLK_DEV_SD VFAT_FS EXFAT_FS; do
    if ! grep -q "^CONFIG_${option}=y$" "$config_file"; then
        echo "FATAL: CONFIG_${option} is not =y after merge" >&2
        grep "CONFIG_${option}" "$config_file" >&2 || true
        exit 1
    fi
done

echo "All critical kernel options are built in."
